"""Render a HealthReport as Markdown."""

from aigis.schemas.checks import Severity
from aigis.schemas.report import HealthReport

_SEVERITY_ICON = {
    Severity.OK: "\u2705",       # green check
    Severity.WARN: "\u26a0\ufe0f",     # warning triangle
    Severity.CRITICAL: "\u274c",  # red X
}


def render_markdown(report: HealthReport) -> str:
    """Convert a HealthReport into a human-readable Markdown string."""
    icon = _SEVERITY_ICON.get(report.overall_severity, "")
    lines: list[str] = []

    lines.append(f"# {icon} AIgis Health Report")
    lines.append("")
    lines.append(f"| Field | Value |")
    lines.append(f"|-------|-------|")
    lines.append(f"| **Run ID** | `{report.run_id}` |")
    lines.append(f"| **Timestamp** | {report.timestamp:%Y-%m-%d %H:%M:%S} |")
    lines.append(f"| **Overall** | {icon} **{report.overall_severity.value}** |")
    lines.append("")

    # -- Checks table --
    lines.append("## Checks")
    lines.append("")
    lines.append("| Status | Check | Message |")
    lines.append("|:------:|-------|---------|")
    for c in report.checks:
        ci = _SEVERITY_ICON.get(c.severity, "")
        msg = c.message.replace("|", "\\|")
        lines.append(f"| {ci} {c.severity.value} | **{c.name}** | {msg} |")
    lines.append("")

    # -- Anomaly explanation --
    if report.anomaly_explanation:
        lines.append("## Analysis")
        lines.append("")
        for paragraph in report.anomaly_explanation.split("\n\n"):
            lines.append(paragraph.strip())
            lines.append("")

    # -- Suggested actions --
    if report.suggested_actions:
        lines.append("## Suggested Actions")
        lines.append("")
        for i, action in enumerate(report.suggested_actions, 1):
            params = ", ".join(f"`{k}={v}`" for k, v in action.params.items())
            lines.append(f"{i}. **{action.action_id}**{f' ({params})' if params else ''}")
            if action.reason:
                lines.append(f"   > {action.reason}")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by AIgis \u2022 run `{report.run_id}`*")
    lines.append("")
    return "\n".join(lines)
