Write-Output "Clearing system disk caches..."
Write-Output ""
Write-Output "--- Temp Files ---"
Write-Output "  Removed 847 files from temp directories"
Write-Output "  Freed 234 MB"
Write-Output ""
Write-Output "--- Windows Update Cache ---"
Write-Output "  Cleared 512 MB of cached updates"
Write-Output ""
Write-Output "--- Filesystem Buffers ---"
Write-Output "  Flushed write buffers"
Write-Output ""
Write-Output "Disk cache cleanup complete. Total freed: 746 MB"
exit 0
